version: 2.1

executors:
  android:
    docker:
      - image: circleci/android:api-29

jobs:
  build:
    executor: android
    steps:
      - checkout
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - run:
          name: Run Tests
          command: ./gradlew test
      - run:
          name: Build APK
          command: ./gradlew assembleDebug

workflows:
  version: 2
  build_android_test:
    jobs:
      - build